# interface_layer/ui_controller.py

from core.brain import think
from user.user_manager import get_user_manager
from system.mode_manager import get_mode_manager
from language.language_manager import get_language_manager
from utils.state import get_state_manager, AssistantState

class UIController:
    """
    This class is the single bridge between a UI and the S1 Assistant's core.
    No UI component should ever directly access any other part of the system.
    """
    def __init__(self):
        self.user_manager = get_user_manager()
        self.mode_manager = get_mode_manager()
        self.lang_manager = get_language_manager()
        self.state_manager = get_state_manager()
        self.last_reply = ""

    def send_command(self, text: str):
        """
        Sends a text command to the assistant's brain and gets a reply.
        This is the primary method for UI text input.
        """
        if not text:
            return None
        
        # The 'think' function contains the entire logic pipeline
        reply, exit_flag = think(text)
        
        self.last_reply = reply
        return reply, exit_flag

    def get_last_reply(self):
        """
        Returns the last reply generated by the assistant.
        Useful for UIs that need to poll for state changes.
        """
        return self.last_reply

    def start_listening(self):
        """
        Signals the core application to start listening for voice commands.
        (Works by changing the global state, which the main loop reacts to).
        """
        print("[UIController] Signal: START LISTENING")
        # Puts the assistant into a state where it's ready to listen for a command
        self.state_manager.set_state(AssistantState.WAITING)
        return True

    def stop_listening(self):
        """
        Signals the core application to stop its current session and return to idle.
        """
        print("[UIController] Signal: STOP LISTENING / GO IDLE")
        self.state_manager.set_state(AssistantState.IDLE)
        return True

    def change_mode(self, mode_name: str):
        """
        Switches the assistant's behavior mode.
        """
        success, message = self.mode_manager.set_mode(mode_name)
        return message

    def switch_user(self, username: str):
        """
        Switches the active user profile.
        """
        success, message = self.user_manager.load_user(username)
        # Reload language pack for the new user
        if success:
            self.lang_manager.load_user_language()
        return message

    def set_language(self, language: str):
        """
        Sets the preferred language for the current user.
        """
        # This mirrors the logic that would happen in the brain
        lang_code_map = {"english": "en", "bengali": "bn", "hindi": "hi"}
        lang_code = lang_code_map.get(language.lower())
        
        if lang_code:
            # The brain would use the memory manager to save this
            # Here we simulate the action for a UI-only interaction
            from memory.memory_manager import get_memory_manager
            memory = get_memory_manager()
            memory.save_memory("profile", "language", lang_code)
            self.lang_manager.load_language(lang_code)
            return self.lang_manager.get_reply("language_switched", language=language)
        return "Unknown language."

# Global instance for easy access from a UI application entry point
S1_UI_CONTROLLER = UIController()

def get_ui_controller():
    return S1_UI_CONTROLLER
