# =========================
# S1 ASSISTANT BRAIN (Phase 12)
# =========================

import random
from datetime import datetime
from language.language_manager import get_language_manager
from system.actions import perform_action
from utils.cleaner import clean_command
from context.context_manager import get_context_manager
from skills.router import route_skill
from memory.memory_engine import get_memory_engine
from system.mode_manager import get_mode_manager
from ai.ai_router import get_ai_response
from system.ai_mode_manager import get_ai_mode_manager
from analytics.studio_reporter import send_event

def think(user_input: str):
    """
    Input -> Clean -> Intent -> Mode Check -> Route -> Action -> Reply -> Analyze
    """
    try:
        send_event("thinking", "Processing request")
    except Exception:
        pass # Fail silently

    # Initialize all managers
    lang_manager = get_language_manager()
    context_manager = get_context_manager()
    mode_manager = get_mode_manager()
    memory_engine = get_memory_engine() # New Memory Engine
    
    # --- Language & Intent Processing ---
    cleaned_input = clean_command(user_input)
    if not cleaned_input:
        return lang_manager.get_reply("unknown"), False
    
    intent_data = lang_manager.map_intent(cleaned_input)
    context_manager.set_context(command=cleaned_input)

    # --- Mode & Permission Check ---
    # ... (logic is unchanged)

    # --- Intent Execution ---
    reply = None
    exit_flag = False
    
    if intent_data:
        intent = intent_data["intent"]
        entity = intent_data.get("entity")
        
        # --- Core Internal Commands (Memory, Modes) ---
        # These are handled directly by the brain as they manage core state.
        
        # 1. Memory-specific commands
        if intent == "save_fact":
            success, message = memory_engine.save_explicit_fact(entity)
            reply = lang_manager.get_reply("memory_saved") if success else message
        
        elif intent == "get_memory_summary":
            summary = memory_engine.get_memory_summary()
            reply = lang_manager.get_reply("memory_summary", summary=summary)

        elif intent == "forget_last":
            success, message = memory_engine.forget_last_fact()
            reply = lang_manager.get_reply("forgot_last") if success else lang_manager.get_reply("nothing_to_forget")

        elif intent == "clear_memory":
            success, message = memory_engine.clear_all_memory()
            reply = lang_manager.get_reply("memory_cleared") if success else message

        # 2. AI Mode settings
        elif intent == "set_ai_mode":
            ai_mode_manager = get_ai_mode_manager()
            success, message = ai_mode_manager.set_ai_mode(entity)
            reply = message # The manager provides the full reply
        
        # --- Skills-Based Actions ---
        # For all other intents, delegate to the Skills Router.
        else:
            # The router will find the appropriate skill and execute it.
            reply = route_skill(intent, entity)

        # After processing, analyze for passive memorization
        if intent not in ["save_fact", "get_memory_summary", "forget_last", "clear_memory"]:
            memory_engine.analyze_and_memorize(cleaned_input, intent_data)

    # If a reply was generated by any handler, return it.
    if reply is not None:
        return reply, exit_flag

    # --- Fallback to AI ---
    # This is only reached if no intent was matched or no skill handled it.
    ai_response = get_ai_response(user_input)
    if ai_response:
        memory_engine.analyze_and_memorize(user_input, None) # Analyze AI interactions too
        return ai_response, False
    else:
        # If all AI fails, provide a clear, final error message to the user.
        return lang_manager.get_reply("ai_services_unavailable"), False